Feature/2 users authentication
joalbertg/cr-API-rails pull request #1
Opened 2019-04-03 06:30 UTC by lisset-orozco

- [ ] create User model, configure shoulda-matchers and user_spec

- [ ] token model

- [ ] token test

- [ ] namespaces for api

- [ ] user_provider_uid from_omniauth

- [ ] user login

- [ ] UserController request test

- [ ] authenticate users

2019-04-04 02:21 UTC, joalbertg requested changes

2019-04-04 02:21 UTC, joalbertg commented on app/controllers/application_controller.rb
> +  def authenticate
refactor code! create memorize method

2019-04-04 02:21 UTC, joalbertg commented on app/controllers/application_controller.rb
> +    if token.nil? || !token.active?
change to return if/unless

2019-04-04 02:21 UTC, joalbertg commented on app/models/token.rb
> +  before_create :generate_token
refactor to service class

2019-04-04 02:21 UTC, joalbertg commented on app/views/api/v1/users/show.json.jbuilder
> +json.(@token, :token)
Add line at end of file

2019-04-05 20:02 UTC, lisset-orozco commented on app/controllers/application_controller.rb
> +    if token.nil? || !token.active?
Done!

2019-04-05 20:02 UTC, lisset-orozco commented on app/views/api/v1/users/show.json.jbuilder
> +json.(@token, :token)
done!

2019-04-05 20:03 UTC, lisset-orozco commented on app/controllers/application_controller.rb
> +  def authenticate
refactor without memoized

2019-04-05 22:00 UTC, lisset-orozco commented on app/models/token.rb
> +  before_create :generate_token
done

2019-04-07 14:10 UTC, joalbertg requested changes

2019-04-07 14:10 UTC, joalbertg commented on app/controllers/api/v1/users_controller.rb
> +        @user = User.from_omniauth(params.fetch(:auth))
refactor equal code

2019-04-07 14:10 UTC, joalbertg commented on app/controllers/api/v1/users_controller.rb
> +        return error_message('param', :auth) if params[:auth].nil?
redundant nil? method.

2019-04-07 14:10 UTC, joalbertg commented on app/controllers/api_v1_controller.rb
> +    @current_user = Token.token_data.user
refactor to .user

2019-04-07 14:10 UTC, joalbertg commented on app/controllers/concerns/error_handler.rb
> +    message = MSG[type.to_sym]
one method!

2019-04-07 14:10 UTC, joalbertg commented on app/controllers/concerns/error_handler.rb
> +    message = { error: message }
two method!

2019-04-07 14:10 UTC, joalbertg commented on app/models/token.rb
> +    def find_token(token_str)
change to token? method

2019-04-07 14:10 UTC, joalbertg commented on app/models/token.rb
> +      @token_data if !@token_data.nil? && @token_data.active?
return `true` or `false`

2019-04-07 14:10 UTC, joalbertg commented on app/views/api/v1/users/show.json.jbuilder
> +json.(@token, :token)
Add line at end of file

2019-04-07 14:12 UTC, lisset-orozco commented on app/views/api/v1/users/show.json.jbuilder
> +json.(@token, :token)
done

2019-04-08 18:42 UTC, lisset-orozco commented on app/controllers/api_v1_controller.rb
> +    @current_user = Token.token_data.user
done

2019-04-08 18:44 UTC, lisset-orozco commented on app/controllers/api/v1/users_controller.rb
> +        @user = User.from_omniauth(params.fetch(:auth))
done

2019-04-08 18:52 UTC, lisset-orozco commented on app/controllers/api/v1/users_controller.rb
> +        return error_message('param', :auth) if params[:auth].nil?
done

2019-04-08 18:53 UTC, lisset-orozco commented on app/models/token.rb
> +    def find_token(token_str)
done

2019-04-08 18:54 UTC, lisset-orozco commented on app/models/token.rb
> +      @token_data if !@token_data.nil? && @token_data.active?
done

2019-04-08 19:46 UTC, lisset-orozco commented on app/controllers/concerns/error_handler.rb
> +    message = { error: message }
done

2019-04-09 02:47 UTC, lisset-orozco commented on app/controllers/concerns/error_handler.rb
> +    message = MSG[type.to_sym]
done

2019-04-09 03:29 UTC, joalbertg approved these changes

2019-04-09 03:30 UTC, merged