Feature/7 answers polls
joalbertg/cr-API-rails pull request #12
Opened 2019-05-10 18:12 UTC by lisset-orozco

- [ ] models and validations

- [ ] controller for the answers

- [ ] show relations

2019-05-10 20:26 UTC, joalbertg requested changes

2019-05-10 20:26 UTC, joalbertg commented on app/controllers/api/v1/my_answers_controller.rb
> +
delete line

2019-05-10 20:26 UTC, joalbertg commented on app/models/my_app.rb
> +    binding.pry
delete binding.pry

2019-05-11 04:58 UTC, lisset-orozco commented on app/controllers/api/v1/my_answers_controller.rb
> +
done

2019-05-11 04:59 UTC, lisset-orozco commented on app/models/my_app.rb
> +    binding.pry
done

2019-05-11 05:02 UTC, joalbertg approved these changes
congratulations!!!

2019-05-11 05:02 UTC, merged